import "@/lib/pixel-retroui-setup.js";
import "./globals.css";

import SideNav from "@/app/ui/sidenav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="absolute -z-10 inset-0 h-full w-full 
bg-[linear-gradient(to_right,#73737320_1px,transparent_1px),linear-gradient(to_bottom,#73737320_1px,transparent_1px)] 
bg-size-[20px_20px] bg-amber-50 antialiased"
    >
      <body className="min-h-full flex justify-center items-center">
        <div className="flex flex-col md:flex-row items-center">
          <SideNav />
          {children}
        </div>
      </body>
    </html>
  );
}
