import localFont from "next/font/local";
const myFont = localFont({
  src: [
    { path: "./fonts/Minecraft.otf", weight: "400", style: "normal" },
    { path: "./fonts/Minecraft-Bold.otf", weight: "700", style: "normal" },
  ],
});

import "@/lib/pixel-retroui-setup.js";
import "./globals.css";

import NavBar from "@/app/ui/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${myFont.className} h-full`}>
      <body className="min-h-screen flex flex-col items-center justify-center">
        <div className="flex flex-col items-center">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
